# Generated by Django 3.2 on 2022-03-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='database',
            new_name='to_be_done',
        ),
    ]
